/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as ProductoIdRouteImport } from './routes/producto.$id'
import { Route as AdminProductosNuevoRouteImport } from './routes/admin.productos.nuevo'
import { Route as AdminProductosIdEditarRouteImport } from './routes/admin.productos.$id.editar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductoIdRoute = ProductoIdRouteImport.update({
  id: '/producto/$id',
  path: '/producto/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosNuevoRoute = AdminProductosNuevoRouteImport.update({
  id: '/admin/productos/nuevo',
  path: '/admin/productos/nuevo',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductosIdEditarRoute = AdminProductosIdEditarRouteImport.update({
  id: '/admin/productos/$id/editar',
  path: '/admin/productos/$id/editar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/productos/$id/editar': typeof AdminProductosIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/productos/$id/editar': typeof AdminProductosIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/producto/$id': typeof ProductoIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/productos/nuevo': typeof AdminProductosNuevoRoute
  '/admin/productos/$id/editar': typeof AdminProductosIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/dashboard'
    | '/producto/$id'
    | '/admin/'
    | '/admin/productos/nuevo'
    | '/admin/productos/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/dashboard'
    | '/producto/$id'
    | '/admin'
    | '/admin/productos/nuevo'
    | '/admin/productos/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/admin/dashboard'
    | '/producto/$id'
    | '/admin/'
    | '/admin/productos/nuevo'
    | '/admin/productos/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  ProductoIdRoute: typeof ProductoIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminProductosNuevoRoute: typeof AdminProductosNuevoRoute
  AdminProductosIdEditarRoute: typeof AdminProductosIdEditarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/producto/$id': {
      id: '/producto/$id'
      path: '/producto/$id'
      fullPath: '/producto/$id'
      preLoaderRoute: typeof ProductoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos/nuevo': {
      id: '/admin/productos/nuevo'
      path: '/admin/productos/nuevo'
      fullPath: '/admin/productos/nuevo'
      preLoaderRoute: typeof AdminProductosNuevoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/productos/$id/editar': {
      id: '/admin/productos/$id/editar'
      path: '/admin/productos/$id/editar'
      fullPath: '/admin/productos/$id/editar'
      preLoaderRoute: typeof AdminProductosIdEditarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  ProductoIdRoute: ProductoIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminProductosNuevoRoute: AdminProductosNuevoRoute,
  AdminProductosIdEditarRoute: AdminProductosIdEditarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
